apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
   name: nginx
   namespace: argocd
spec:
   project: detault
   source: 
      repoURL: 'https://github.com/bizvoguedigital/argocd.git'   
      path: manifest
      targetRevision: main 
   destination: 
      server: 'https://kubernetes.default.svc'  
      namespace: default 
   syncPolicy:
      automated: 
          selfHeal: true 
          prune: true  

